### ISSUE TITLE
State of this project ?

### ISSUE THREAD

**Issue by Socolin** [Settler/resharper-specflow#14]
Hello,

I'm interested in having a Specflow plugin for rider, with at least highlighting and navigate between step and step definitions.

I experimented the code on the pull request here https://github.com/threefjefff/resharper-specflow/pull/1 by @threefjefff it was looking good, (I was not able to get the Go to steps working). I was wondering if you plan to continue this or if I could take a look ?

I was able to start the plugin in version 2020.3.2, the only "questionnable"  things I had to do was to rename the language name to avoid duplicate with the CucumberJs plugin (Event after disabling it I got the errors)

Before I start spending time in this I would like to  know if there are WIP stuff or issues that need to be addressed first, and if you are not currently working on it (to avoid working for nothing :p) or if you have any information to share about this.

**Comment by Settler** [comment]
Hi @Socolin.

@threefjefff has forked this repo and gone further than I am. So I recommend to investigate his repo, because I'm not working on this plugin right now.

About CucumberJs. While I was working on this plugin I disabled two plugins in Rider which were enabled by default:
Cucumber and Gherkin.
In evolution of this plugin, I saw possibility to warn developer about enabled conflicting plugins or disable them programmatically when my plugin will load.

**Comment by Socolin** [comment]
Hello,

Just a message to keep you updated.

So I take a look to the branch of threefjeff and I notice some problems:
- It was not matching regex correctly (only (.*) when parameter got the `"` arround)
- It was referencing toward `IAttribute` that is not a `IDeclaredElement` so it's not possible to use the whole `Go to declaraton / Find usage` built in
- The thing to store references in the data bag on nodes was never emptied so each time it scans, it added more and more referencing.

So I tried to start again from this repository following another path. I validate that path with people in the jetbrains slack channel and here I got a version working with the following features
- Go to declaration from specflow files to c# (Find usages will need some works due to the fact it's using regex and so some default behaviour need some `override`)
- Highligthing steps that does not match any step definition in the C#

To do that I started by implementing a Cache that will keep the list of step definition up to date with the little of work when something changes (only affected files are parsed again)

Then to get the `Go to declaration` working it was required to define a IReference for the `GherkinStep` and returns it in `GetFirstClassReferences()` and after adding a config in plugin,xml Go to declaration works
This need to be refined to only show usable action in Specflow (`Go to` menu show too much things currently)
```
<backend.actions.support language="Gherkin" implementationClass="com.jetbrains.rider.actions.RiderActionSupportPolicy" />
```
The cache is used to `Resolve()` the reference.


I've planned to continue working on this to implements other missing feature. 

I planned to publish the plugin on the Rider Marketplace soon (probably next week, since I'm going to need to at works really soon)

**Comment by Socolin** [comment]
It seems it was just the resharper part https://plugins.jetbrains.com/plugin/13509-specflow-support so for now it's not a blocker.

In immediate future I only plan to release Rider plugin, since there is already an extension on VS for specflow and I'm mainly working on Linux so it'll be hard to test :p but I have access to a windows so I'll take a look at this later if the need is here (or if I add some feature not present in the VS plugin). However I'll try to find some time to merge your branch.

About the plugin progress, I added a quick fix to create new step when it does not exists

**Comment by mariostnr** [comment]
Quick update:

[SpecFlow](https://github.com/SpecFlowOSS/SpecFlow.Rider) is teaming up with @Socolin on developing and maintaining the forked JetBrains Rider extension linked above. This means, that the extension will get additional features and fixes quicker and will work with future versions of Rider.

If you find a bug or have an idea to further improve the extension please take a look at our official and maintained repository: https://github.com/SpecFlowOSS/SpecFlow.Rider

**Comment by Settler** [comment]
@mariostnr, @Socolin thank you! I'm glad that we've finally done this big step to Rider and can use SpecFlow there in full force.
I'll close this issue because no future work is planned on this repo.
